[2025-03-25T19:14:13.860+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/test.py
[2025-03-25T19:14:13.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:14:13.862+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:14:13.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:14:13.955+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:14:13.954+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:14:13.956+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:14:14.013+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:14:14.013+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:14:14.019+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:14:14.019+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:14:14.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.259 seconds
[2025-03-25T19:14:44.338+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/test.py
[2025-03-25T19:14:44.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:14:44.343+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:14:44.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:14:44.437+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:14:44.437+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:14:44.439+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:14:44.452+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:14:44.452+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:14:44.459+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:14:44.459+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:14:44.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T19:15:14.651+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/test.py
[2025-03-25T19:15:14.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:15:14.657+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:15:14.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:15:14.752+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:15:14.752+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:15:14.753+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:15:14.766+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:15:14.766+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:15:14.773+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:15:14.773+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:15:14.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.138 seconds
[2025-03-25T19:15:44.959+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/test.py
[2025-03-25T19:15:44.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:15:44.963+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:15:44.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:15:45.052+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:15:45.051+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:15:45.053+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:15:45.065+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:15:45.065+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:15:45.072+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:15:45.072+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:15:45.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.123 seconds
[2025-03-25T19:16:15.236+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/test.py
[2025-03-25T19:16:15.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:16:15.241+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:16:15.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:16:15.335+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:16:15.334+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:16:15.336+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:16:15.349+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:16:15.349+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:16:15.356+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:16:15.356+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:16:15.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:16:45.536+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/test.py
[2025-03-25T19:16:45.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:16:45.538+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:16:45.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:16:45.630+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:16:45.630+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:16:45.631+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:16:45.644+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:16:45.644+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:16:45.651+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:16:45.651+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:16:45.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:17:15.821+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/test.py
[2025-03-25T19:17:15.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:17:15.826+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:17:15.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:17:15.920+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:17:15.919+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:17:15.921+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:17:15.934+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:17:15.934+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:17:15.941+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:17:15.941+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:17:16.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.231 seconds
[2025-03-25T19:17:46.186+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/test.py
[2025-03-25T19:17:46.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:17:46.192+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:17:46.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:17:46.285+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:17:46.284+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:17:46.286+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:17:46.299+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:17:46.299+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:17:46.403+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:17:46.403+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:17:46.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.228 seconds
[2025-03-25T19:18:16.537+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/test.py
[2025-03-25T19:18:16.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:18:16.538+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:18:16.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:18:16.632+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:18:16.632+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:18:16.634+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:18:16.743+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:18:16.743+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:18:16.750+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:18:16.750+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:18:16.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-03-25T19:18:46.980+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/test.py
[2025-03-25T19:18:46.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:18:46.985+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:18:46.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:18:47.175+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:18:47.174+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:18:47.176+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:18:47.187+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:18:47.187+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:18:47.193+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:18:47.193+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:18:47.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-03-25T19:19:17.421+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/test.py
[2025-03-25T19:19:17.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:19:17.422+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:19:17.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:19:17.517+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:19:17.516+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:19:17.518+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:19:17.531+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:19:17.531+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:19:17.538+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:19:17.538+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:19:17.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T19:19:47.718+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/test.py
[2025-03-25T19:19:47.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:19:47.720+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:19:47.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:19:47.814+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:19:47.813+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:19:47.815+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:19:47.828+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:19:47.828+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:19:47.836+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:19:47.836+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:19:47.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-03-25T19:20:18.866+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/test.py
[2025-03-25T19:20:18.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:20:18.871+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:20:18.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:20:18.964+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:20:18.964+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:20:18.965+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:20:18.978+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:20:18.978+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:20:19.082+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:20:19.082+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:20:19.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.228 seconds
[2025-03-25T19:20:49.609+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/test.py
[2025-03-25T19:20:49.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:20:49.614+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:20:49.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:20:49.708+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:20:49.708+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:20:49.710+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:20:49.833+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:20:49.833+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:20:49.840+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:20:49.839+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:20:49.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.248 seconds
[2025-03-25T19:21:20.119+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/test.py
[2025-03-25T19:21:20.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:21:20.120+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:21:20.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:21:20.318+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:21:20.317+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:21:20.319+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:21:20.331+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:21:20.331+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:21:20.337+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:21:20.337+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:21:20.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-03-25T19:21:50.562+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/test.py
[2025-03-25T19:21:50.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:21:50.563+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:21:50.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:21:50.659+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:21:50.658+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:21:50.660+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:21:50.673+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:21:50.673+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:21:50.680+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:21:50.680+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:21:50.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:22:21.590+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/test.py
[2025-03-25T19:22:21.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:22:21.594+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:22:21.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:22:21.692+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:22:21.692+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:22:21.694+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:22:21.707+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:22:21.707+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:22:21.782+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:22:21.782+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:22:21.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.205 seconds
[2025-03-25T19:22:51.914+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/test.py
[2025-03-25T19:22:51.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:22:51.919+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:22:51.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:22:52.013+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:22:52.013+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:22:52.015+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:22:52.121+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:22:52.121+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:22:52.128+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:22:52.128+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:22:52.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.224 seconds
[2025-03-25T19:23:22.276+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/test.py
[2025-03-25T19:23:22.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:23:22.280+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:23:22.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:23:22.373+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:23:22.372+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:23:22.374+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:23:22.463+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:23:22.463+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:23:22.469+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:23:22.469+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:23:22.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.212 seconds
[2025-03-25T19:23:52.768+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/test.py
[2025-03-25T19:23:52.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:23:52.773+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:23:52.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:23:52.965+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:23:52.964+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:23:52.966+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:23:52.977+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:23:52.977+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:23:52.983+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:23:52.983+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:23:52.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-03-25T19:24:23.127+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/test.py
[2025-03-25T19:24:23.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:24:23.128+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:24:23.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:24:23.222+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:24:23.222+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:24:23.223+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:24:23.236+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:24:23.236+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:24:23.243+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:24:23.243+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:24:23.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T19:24:53.389+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/test.py
[2025-03-25T19:24:53.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:24:53.390+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:24:53.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:24:53.483+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:24:53.482+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:24:53.484+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:24:53.497+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:24:53.497+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:24:53.602+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:24:53.602+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:24:53.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-03-25T19:25:23.791+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/test.py
[2025-03-25T19:25:23.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:25:23.794+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:25:23.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:25:23.888+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:25:23.888+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:25:23.890+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:25:23.903+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:25:23.902+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:25:23.976+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:25:23.976+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:25:23.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.204 seconds
[2025-03-25T19:25:54.144+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/test.py
[2025-03-25T19:25:54.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:25:54.147+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:25:54.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:25:54.240+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:25:54.239+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:25:54.242+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:25:54.350+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:25:54.350+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:25:54.356+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:25:54.356+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:25:54.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-03-25T19:26:24.555+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/test.py
[2025-03-25T19:26:24.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:26:24.556+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:26:24.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:26:24.748+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:26:24.747+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:26:24.749+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:26:24.760+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:26:24.760+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:26:24.766+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:26:24.766+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:26:24.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.224 seconds
[2025-03-25T19:26:54.961+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/test.py
[2025-03-25T19:26:54.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:26:54.965+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:26:54.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:26:55.158+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:26:55.158+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:26:55.160+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:26:55.171+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:26:55.171+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:26:55.177+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:26:55.177+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:26:55.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-03-25T19:27:25.384+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/test.py
[2025-03-25T19:27:25.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:27:25.387+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:27:25.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:27:25.477+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:27:25.477+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:27:25.478+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:27:25.491+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:27:25.491+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:27:25.498+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:27:25.498+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:27:25.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.192 seconds
[2025-03-25T19:27:55.957+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/test.py
[2025-03-25T19:27:55.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:27:55.958+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:27:55.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:27:56.051+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:27:56.051+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:27:56.053+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:27:56.066+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:27:56.066+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:27:56.140+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:27:56.140+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:27:56.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.198 seconds
[2025-03-25T19:28:26.536+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/test.py
[2025-03-25T19:28:26.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:28:26.537+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:28:26.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:28:26.631+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:28:26.630+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:28:26.632+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:28:26.744+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:28:26.744+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:28:26.750+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:28:26.750+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:28:26.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.224 seconds
[2025-03-25T19:28:57.114+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/test.py
[2025-03-25T19:28:57.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:28:57.115+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:28:57.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:28:57.318+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:28:57.318+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:28:57.319+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:28:57.330+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:28:57.330+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:28:57.336+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:28:57.336+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:28:57.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.232 seconds
[2025-03-25T19:29:27.705+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/test.py
[2025-03-25T19:29:27.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:29:27.706+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:29:27.706+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:29:27.895+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:29:27.895+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:29:27.897+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:29:27.907+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:29:27.907+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:29:27.913+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:29:27.913+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:29:27.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.220 seconds
[2025-03-25T19:29:58.192+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/test.py
[2025-03-25T19:29:58.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:29:58.193+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:29:58.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:29:58.287+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:29:58.287+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:29:58.289+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:29:58.302+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:29:58.302+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:29:58.310+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:29:58.310+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:29:58.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.136 seconds
[2025-03-25T19:30:28.639+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/test.py
[2025-03-25T19:30:28.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:30:28.640+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:30:28.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:30:28.734+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:30:28.733+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:30:28.735+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:30:28.748+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:30:28.748+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:30:28.756+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:30:28.756+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:30:28.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:30:59.069+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/test.py
[2025-03-25T19:30:59.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:30:59.070+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:30:59.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:30:59.163+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:30:59.163+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:30:59.164+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:30:59.178+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:30:59.178+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:30:59.186+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:30:59.185+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:30:59.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:31:29.511+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/test.py
[2025-03-25T19:31:29.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:31:29.512+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:31:29.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:31:29.606+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:31:29.606+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:31:29.608+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:31:29.621+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:31:29.621+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:31:29.628+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:31:29.628+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:31:29.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.129 seconds
[2025-03-25T19:31:59.935+0000] {processor.py:186} INFO - Started process (PID=482) to work on /opt/airflow/dags/test.py
[2025-03-25T19:31:59.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:31:59.936+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:31:59.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:32:00.029+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:32:00.029+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:32:00.031+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:32:00.044+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:32:00.044+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:32:00.052+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:32:00.052+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:32:00.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.128 seconds
[2025-03-25T19:32:30.366+0000] {processor.py:186} INFO - Started process (PID=493) to work on /opt/airflow/dags/test.py
[2025-03-25T19:32:30.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:32:30.367+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:32:30.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:32:30.461+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:32:30.460+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:32:30.462+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:32:30.476+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:32:30.476+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:32:30.484+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:32:30.484+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:32:30.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.130 seconds
[2025-03-25T19:33:00.809+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/test.py
[2025-03-25T19:33:00.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:33:00.811+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:33:00.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:33:00.905+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:33:00.905+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:33:00.906+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:33:00.920+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:33:00.919+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:33:00.927+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:33:00.927+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:33:00.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:33:31.250+0000] {processor.py:186} INFO - Started process (PID=515) to work on /opt/airflow/dags/test.py
[2025-03-25T19:33:31.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:33:31.251+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:33:31.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:33:31.345+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:33:31.344+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:33:31.346+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:33:31.360+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:33:31.359+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:33:31.367+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:33:31.367+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:33:31.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:34:01.677+0000] {processor.py:186} INFO - Started process (PID=526) to work on /opt/airflow/dags/test.py
[2025-03-25T19:34:01.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:34:01.678+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:34:01.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:34:01.771+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:34:01.770+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:34:01.772+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:34:01.785+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:34:01.785+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:34:01.792+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:34:01.792+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:34:01.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.134 seconds
[2025-03-25T19:34:32.108+0000] {processor.py:186} INFO - Started process (PID=536) to work on /opt/airflow/dags/test.py
[2025-03-25T19:34:32.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:34:32.109+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:34:32.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:34:32.203+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:34:32.203+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:34:32.204+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:34:32.218+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:34:32.218+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:34:32.225+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:34:32.225+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:34:32.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:35:02.557+0000] {processor.py:186} INFO - Started process (PID=548) to work on /opt/airflow/dags/test.py
[2025-03-25T19:35:02.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:35:02.558+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:35:02.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:35:02.651+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:35:02.651+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:35:02.653+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:35:02.666+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:35:02.666+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:35:02.673+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:35:02.673+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:35:02.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.128 seconds
[2025-03-25T19:35:32.984+0000] {processor.py:186} INFO - Started process (PID=559) to work on /opt/airflow/dags/test.py
[2025-03-25T19:35:32.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:35:32.985+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:35:32.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:35:33.076+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:35:33.076+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:35:33.078+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:35:33.091+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:35:33.091+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:35:33.100+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:35:33.100+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:35:33.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.128 seconds
[2025-03-25T19:36:03.880+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/test.py
[2025-03-25T19:36:03.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:36:03.885+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:36:03.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:36:03.978+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:36:03.977+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:36:03.979+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:36:03.992+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:36:03.992+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:36:03.999+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:36:03.999+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:36:04.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.138 seconds
[2025-03-25T19:36:34.482+0000] {processor.py:186} INFO - Started process (PID=592) to work on /opt/airflow/dags/test.py
[2025-03-25T19:36:34.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:36:34.483+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:36:34.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:36:34.578+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:36:34.577+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:36:34.579+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:36:34.592+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:36:34.592+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:36:34.599+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:36:34.599+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:36:34.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T19:37:04.787+0000] {processor.py:186} INFO - Started process (PID=606) to work on /opt/airflow/dags/test.py
[2025-03-25T19:37:04.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:37:04.791+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:37:04.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:37:04.884+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:37:04.884+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:37:04.886+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:37:04.899+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:37:04.899+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:37:04.906+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:37:04.906+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:37:04.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:37:35.104+0000] {processor.py:186} INFO - Started process (PID=617) to work on /opt/airflow/dags/test.py
[2025-03-25T19:37:35.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:37:35.108+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:37:35.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:37:35.203+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:37:35.203+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:37:35.205+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:37:35.218+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:37:35.218+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:37:35.225+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:37:35.225+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:37:35.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:38:05.721+0000] {processor.py:186} INFO - Started process (PID=633) to work on /opt/airflow/dags/test.py
[2025-03-25T19:38:05.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:38:05.725+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:38:05.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:38:05.819+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:38:05.819+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:38:05.821+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:38:05.833+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:38:05.833+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:38:05.841+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:38:05.841+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:38:05.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.138 seconds
[2025-03-25T19:38:36.304+0000] {processor.py:186} INFO - Started process (PID=648) to work on /opt/airflow/dags/test.py
[2025-03-25T19:38:36.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:38:36.308+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:38:36.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:38:36.402+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:38:36.402+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:38:36.404+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:38:36.418+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:38:36.418+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:38:36.425+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:38:36.425+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:38:36.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T19:39:06.877+0000] {processor.py:186} INFO - Started process (PID=661) to work on /opt/airflow/dags/test.py
[2025-03-25T19:39:06.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:39:06.878+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:39:06.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:39:06.974+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:39:06.973+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:39:06.975+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:39:06.988+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:39:06.988+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:39:06.996+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:39:06.996+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:39:07.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:39:37.066+0000] {processor.py:186} INFO - Started process (PID=682) to work on /opt/airflow/dags/test.py
[2025-03-25T19:39:37.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:39:37.070+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:39:37.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:39:37.165+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:39:37.165+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:39:37.166+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:39:37.179+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:39:37.179+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:39:37.187+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:39:37.187+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:39:37.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T19:40:07.932+0000] {processor.py:186} INFO - Started process (PID=700) to work on /opt/airflow/dags/test.py
[2025-03-25T19:40:07.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:40:07.936+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:40:07.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:40:08.031+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:40:08.030+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:40:08.032+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:40:08.044+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:40:08.044+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:40:08.051+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:40:08.051+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:40:08.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.130 seconds
[2025-03-25T19:40:38.207+0000] {processor.py:186} INFO - Started process (PID=711) to work on /opt/airflow/dags/test.py
[2025-03-25T19:40:38.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:40:38.211+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:40:38.211+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:40:38.306+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:40:38.305+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:40:38.307+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:40:38.320+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:40:38.320+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:40:38.328+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:40:38.328+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:40:38.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T19:41:08.765+0000] {processor.py:186} INFO - Started process (PID=724) to work on /opt/airflow/dags/test.py
[2025-03-25T19:41:08.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:41:08.769+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:41:08.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:41:08.864+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:41:08.863+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:41:08.865+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:41:08.878+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:41:08.878+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:41:08.885+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:41:08.885+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:41:08.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T19:41:38.934+0000] {processor.py:186} INFO - Started process (PID=741) to work on /opt/airflow/dags/test.py
[2025-03-25T19:41:38.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:41:38.938+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:41:38.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:41:39.032+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:41:39.032+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:41:39.034+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:41:39.047+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:41:39.047+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:41:39.054+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:41:39.054+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:41:39.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T19:42:09.956+0000] {processor.py:186} INFO - Started process (PID=761) to work on /opt/airflow/dags/test.py
[2025-03-25T19:42:09.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:42:09.957+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:42:09.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:42:10.049+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:42:10.049+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:42:10.050+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:42:10.062+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:42:10.062+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:42:10.069+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:42:10.069+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:42:10.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.124 seconds
[2025-03-25T19:42:40.291+0000] {processor.py:186} INFO - Started process (PID=781) to work on /opt/airflow/dags/test.py
[2025-03-25T19:42:40.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:42:40.292+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:42:40.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:42:40.387+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:42:40.386+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:42:40.388+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:42:40.401+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:42:40.401+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:42:40.409+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:42:40.409+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:42:40.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:43:10.703+0000] {processor.py:186} INFO - Started process (PID=792) to work on /opt/airflow/dags/test.py
[2025-03-25T19:43:10.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:43:10.704+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:43:10.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:43:10.800+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:43:10.799+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:43:10.801+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:43:10.814+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:43:10.814+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:43:10.822+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:43:10.822+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:43:10.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T19:43:41.106+0000] {processor.py:186} INFO - Started process (PID=803) to work on /opt/airflow/dags/test.py
[2025-03-25T19:43:41.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:43:41.107+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:43:41.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:43:41.201+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:43:41.200+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:43:41.202+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:43:41.216+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:43:41.216+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:43:41.223+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:43:41.223+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:43:41.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.136 seconds
[2025-03-25T19:44:11.392+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/dags/test.py
[2025-03-25T19:44:11.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:44:11.396+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:44:11.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:44:11.490+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:44:11.489+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:44:11.491+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:44:11.504+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:44:11.503+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:44:11.511+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:44:11.511+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:44:11.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.130 seconds
[2025-03-25T19:44:41.664+0000] {processor.py:186} INFO - Started process (PID=826) to work on /opt/airflow/dags/test.py
[2025-03-25T19:44:41.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:44:41.666+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:44:41.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:44:41.758+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:44:41.757+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:44:41.759+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:44:41.772+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:44:41.772+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:44:41.779+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:44:41.779+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:44:41.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:45:11.952+0000] {processor.py:186} INFO - Started process (PID=837) to work on /opt/airflow/dags/test.py
[2025-03-25T19:45:11.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:45:11.956+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:45:11.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:45:12.042+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:45:12.041+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:45:12.043+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:45:12.055+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:45:12.055+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:45:12.062+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:45:12.062+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:45:12.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.121 seconds
[2025-03-25T19:45:42.228+0000] {processor.py:186} INFO - Started process (PID=848) to work on /opt/airflow/dags/test.py
[2025-03-25T19:45:42.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:45:42.231+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:45:42.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:45:42.318+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:45:42.318+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:45:42.320+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:45:42.333+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:45:42.333+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:45:42.341+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:45:42.340+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:45:42.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:46:12.510+0000] {processor.py:186} INFO - Started process (PID=859) to work on /opt/airflow/dags/test.py
[2025-03-25T19:46:12.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:46:12.513+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:46:12.513+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:46:12.607+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:46:12.606+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:46:12.608+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:46:12.622+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:46:12.622+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:46:12.629+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:46:12.629+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:46:12.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.140 seconds
[2025-03-25T19:46:42.798+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/test.py
[2025-03-25T19:46:42.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:46:42.803+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:46:42.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:46:42.897+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:46:42.897+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:46:42.899+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:46:42.911+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:46:42.911+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:46:42.919+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:46:42.919+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:46:42.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.138 seconds
[2025-03-25T19:47:13.084+0000] {processor.py:186} INFO - Started process (PID=881) to work on /opt/airflow/dags/test.py
[2025-03-25T19:47:13.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:47:13.088+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:47:13.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:47:13.183+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:47:13.183+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:47:13.184+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:47:13.197+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:47:13.197+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:47:13.205+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:47:13.204+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:47:13.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:47:43.944+0000] {processor.py:186} INFO - Started process (PID=898) to work on /opt/airflow/dags/test.py
[2025-03-25T19:47:43.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:47:43.946+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:47:43.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:47:44.041+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:47:44.041+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:47:44.043+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:47:44.055+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:47:44.055+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:47:44.063+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:47:44.063+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:47:44.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.130 seconds
[2025-03-25T19:48:14.111+0000] {processor.py:186} INFO - Started process (PID=919) to work on /opt/airflow/dags/test.py
[2025-03-25T19:48:14.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:48:14.112+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:48:14.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:48:14.201+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:48:14.201+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:48:14.202+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:48:14.215+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:48:14.215+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:48:14.223+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:48:14.223+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:48:14.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.129 seconds
[2025-03-25T19:48:44.404+0000] {processor.py:186} INFO - Started process (PID=930) to work on /opt/airflow/dags/test.py
[2025-03-25T19:48:44.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:48:44.405+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:48:44.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:48:44.499+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:48:44.498+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:48:44.500+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:48:44.513+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:48:44.513+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:48:44.521+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:48:44.521+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:48:44.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T19:49:14.582+0000] {processor.py:186} INFO - Started process (PID=950) to work on /opt/airflow/dags/test.py
[2025-03-25T19:49:14.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:49:14.583+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:49:14.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:49:14.680+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:49:14.679+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:49:14.681+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:49:14.695+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:49:14.695+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:49:14.702+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:49:14.702+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:49:14.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:49:44.992+0000] {processor.py:186} INFO - Started process (PID=961) to work on /opt/airflow/dags/test.py
[2025-03-25T19:49:44.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:49:44.993+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:49:44.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:49:45.087+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:49:45.086+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:49:45.088+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:49:45.101+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:49:45.101+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:49:45.109+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:49:45.109+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:49:45.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.128 seconds
[2025-03-25T19:50:15.402+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/test.py
[2025-03-25T19:50:15.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:50:15.403+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:50:15.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:50:15.502+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:50:15.501+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:50:15.503+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:50:15.517+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:50:15.517+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:50:15.525+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:50:15.525+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:50:15.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.134 seconds
[2025-03-25T19:50:45.821+0000] {processor.py:186} INFO - Started process (PID=983) to work on /opt/airflow/dags/test.py
[2025-03-25T19:50:45.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:50:45.822+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:50:45.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:50:45.924+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:50:45.924+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:50:45.926+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:50:45.939+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:50:45.939+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:50:45.946+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:50:45.946+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:50:45.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:51:16.239+0000] {processor.py:186} INFO - Started process (PID=994) to work on /opt/airflow/dags/test.py
[2025-03-25T19:51:16.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:51:16.240+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:51:16.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:51:16.333+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:51:16.333+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:51:16.335+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:51:16.348+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:51:16.348+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:51:16.355+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:51:16.355+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:51:16.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.136 seconds
[2025-03-25T19:51:47.155+0000] {processor.py:186} INFO - Started process (PID=1013) to work on /opt/airflow/dags/test.py
[2025-03-25T19:51:47.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:51:47.156+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:51:47.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:51:47.249+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:51:47.248+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:51:47.250+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:51:47.263+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:51:47.263+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:51:47.270+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:51:47.270+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:51:47.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.126 seconds
[2025-03-25T19:52:17.751+0000] {processor.py:186} INFO - Started process (PID=1028) to work on /opt/airflow/dags/test.py
[2025-03-25T19:52:17.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:52:17.755+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:52:17.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:52:17.851+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:52:17.850+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:52:17.852+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:52:17.865+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:52:17.865+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:52:17.873+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:52:17.872+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:52:17.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:52:48.043+0000] {processor.py:186} INFO - Started process (PID=1045) to work on /opt/airflow/dags/test.py
[2025-03-25T19:52:48.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:52:48.047+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:52:48.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:52:48.142+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:52:48.141+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:52:48.143+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:52:48.156+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:52:48.156+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:52:48.164+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:52:48.164+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:52:48.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:53:18.329+0000] {processor.py:186} INFO - Started process (PID=1056) to work on /opt/airflow/dags/test.py
[2025-03-25T19:53:18.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:53:18.334+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:53:18.333+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:53:18.429+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:53:18.428+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:53:18.430+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:53:18.443+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:53:18.443+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:53:18.451+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:53:18.451+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:53:18.465+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T19:53:48.629+0000] {processor.py:186} INFO - Started process (PID=1067) to work on /opt/airflow/dags/test.py
[2025-03-25T19:53:48.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:53:48.633+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:53:48.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:53:48.729+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:53:48.728+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:53:48.730+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:53:48.744+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:53:48.744+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:53:48.751+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:53:48.751+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:53:48.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T19:54:18.921+0000] {processor.py:186} INFO - Started process (PID=1078) to work on /opt/airflow/dags/test.py
[2025-03-25T19:54:18.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:54:18.926+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:54:18.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:54:19.021+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:54:19.021+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:54:19.023+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:54:19.036+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:54:19.036+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:54:19.043+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:54:19.043+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:54:19.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T19:54:49.280+0000] {processor.py:186} INFO - Started process (PID=1097) to work on /opt/airflow/dags/test.py
[2025-03-25T19:54:49.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:54:49.283+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:54:49.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:54:49.378+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:54:49.377+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:54:49.379+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:54:49.392+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:54:49.392+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:54:49.399+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:54:49.399+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:54:49.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:55:19.891+0000] {processor.py:186} INFO - Started process (PID=1115) to work on /opt/airflow/dags/test.py
[2025-03-25T19:55:19.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:55:19.896+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:55:19.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:55:19.990+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:55:19.989+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:55:19.991+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:55:20.004+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:55:20.004+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:55:20.011+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:55:20.011+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:55:20.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T19:55:50.484+0000] {processor.py:186} INFO - Started process (PID=1130) to work on /opt/airflow/dags/test.py
[2025-03-25T19:55:50.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:55:50.488+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:55:50.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:55:50.583+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:55:50.582+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:55:50.584+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:55:50.597+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:55:50.597+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:55:50.604+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:55:50.604+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:55:50.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T19:56:20.664+0000] {processor.py:186} INFO - Started process (PID=1149) to work on /opt/airflow/dags/test.py
[2025-03-25T19:56:20.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:56:20.665+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:56:20.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:56:20.758+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:56:20.757+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:56:20.759+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:56:20.773+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:56:20.773+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:56:20.780+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:56:20.780+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:56:20.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.130 seconds
[2025-03-25T19:56:51.798+0000] {processor.py:186} INFO - Started process (PID=1182) to work on /opt/airflow/dags/test.py
[2025-03-25T19:56:51.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:56:51.801+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:56:51.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:56:51.894+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:56:51.894+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:56:51.895+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:56:51.908+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:56:51.908+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:56:51.915+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:56:51.915+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:56:51.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:57:22.415+0000] {processor.py:186} INFO - Started process (PID=1198) to work on /opt/airflow/dags/test.py
[2025-03-25T19:57:22.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:57:22.416+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:57:22.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:57:22.508+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:57:22.507+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:57:22.509+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:57:22.521+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:57:22.521+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:57:22.529+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:57:22.529+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:57:22.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T19:57:53.334+0000] {processor.py:186} INFO - Started process (PID=1218) to work on /opt/airflow/dags/test.py
[2025-03-25T19:57:53.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:57:53.338+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:57:53.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:57:53.433+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:57:53.432+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:57:53.434+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:57:53.446+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:57:53.446+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:57:53.453+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:57:53.453+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:57:53.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.137 seconds
[2025-03-25T19:58:23.519+0000] {processor.py:186} INFO - Started process (PID=1238) to work on /opt/airflow/dags/test.py
[2025-03-25T19:58:23.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:58:23.520+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:58:23.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:58:23.616+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:58:23.615+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:58:23.617+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:58:23.630+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:58:23.630+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:58:23.638+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:58:23.638+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:58:23.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.130 seconds
[2025-03-25T19:58:54.085+0000] {processor.py:186} INFO - Started process (PID=1251) to work on /opt/airflow/dags/test.py
[2025-03-25T19:58:54.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:58:54.090+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:58:54.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:58:54.184+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:58:54.183+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:58:54.185+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:58:54.198+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:58:54.198+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:58:54.205+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:58:54.205+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:58:54.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T19:59:24.255+0000] {processor.py:186} INFO - Started process (PID=1270) to work on /opt/airflow/dags/test.py
[2025-03-25T19:59:24.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:59:24.259+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:59:24.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:59:24.354+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:59:24.353+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:59:24.356+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:59:24.369+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:59:24.368+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:59:24.375+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:59:24.375+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:59:24.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T19:59:54.462+0000] {processor.py:186} INFO - Started process (PID=1294) to work on /opt/airflow/dags/test.py
[2025-03-25T19:59:54.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T19:59:54.466+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:59:54.466+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T19:59:54.561+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:59:54.561+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T19:59:54.563+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T19:59:54.577+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:59:54.577+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T19:59:54.584+0000] {logging_mixin.py:190} INFO - [2025-03-25T19:59:54.584+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T19:59:54.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.134 seconds
[2025-03-25T20:00:24.643+0000] {processor.py:186} INFO - Started process (PID=1311) to work on /opt/airflow/dags/test.py
[2025-03-25T20:00:24.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:00:24.647+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:00:24.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:00:24.740+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:00:24.739+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:00:24.741+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:00:24.756+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:00:24.756+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:00:24.763+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:00:24.763+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:00:24.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T20:00:54.819+0000] {processor.py:186} INFO - Started process (PID=1333) to work on /opt/airflow/dags/test.py
[2025-03-25T20:00:54.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:00:54.823+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:00:54.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:00:54.917+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:00:54.917+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:00:54.919+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:00:54.932+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:00:54.932+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:00:54.939+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:00:54.939+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:00:54.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T20:01:25.097+0000] {processor.py:186} INFO - Started process (PID=1344) to work on /opt/airflow/dags/test.py
[2025-03-25T20:01:25.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:01:25.098+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:01:25.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:01:25.192+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:01:25.191+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:01:25.193+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:01:25.206+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:01:25.206+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:01:25.213+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:01:25.213+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:01:25.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.134 seconds
[2025-03-25T20:01:55.394+0000] {processor.py:186} INFO - Started process (PID=1355) to work on /opt/airflow/dags/test.py
[2025-03-25T20:01:55.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:01:55.402+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:01:55.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:01:55.488+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:01:55.487+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:01:55.489+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:01:55.502+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:01:55.502+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:01:55.508+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:01:55.508+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:01:55.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T20:02:25.673+0000] {processor.py:186} INFO - Started process (PID=1366) to work on /opt/airflow/dags/test.py
[2025-03-25T20:02:25.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:02:25.675+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:02:25.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:02:25.768+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:02:25.767+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:02:25.769+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:02:25.783+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:02:25.783+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:02:25.790+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:02:25.790+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:02:25.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T20:02:55.954+0000] {processor.py:186} INFO - Started process (PID=1377) to work on /opt/airflow/dags/test.py
[2025-03-25T20:02:55.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:02:55.959+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:02:55.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:02:56.053+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:02:56.053+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:02:56.054+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:02:56.067+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:02:56.067+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:02:56.075+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:02:56.075+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:02:56.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T20:03:26.234+0000] {processor.py:186} INFO - Started process (PID=1388) to work on /opt/airflow/dags/test.py
[2025-03-25T20:03:26.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:03:26.241+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:03:26.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:03:26.326+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:03:26.326+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:03:26.328+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:03:26.340+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:03:26.340+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:03:26.347+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:03:26.347+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:03:26.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T20:03:56.510+0000] {processor.py:186} INFO - Started process (PID=1399) to work on /opt/airflow/dags/test.py
[2025-03-25T20:03:56.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:03:56.513+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:03:56.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:03:56.611+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:03:56.610+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:03:56.612+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:03:56.625+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:03:56.625+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:03:56.632+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:03:56.632+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:03:56.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.135 seconds
[2025-03-25T20:04:26.782+0000] {processor.py:186} INFO - Started process (PID=1410) to work on /opt/airflow/dags/test.py
[2025-03-25T20:04:26.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:04:26.786+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:04:26.786+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:04:26.881+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:04:26.881+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:04:26.883+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:04:26.895+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:04:26.895+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:04:26.903+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:04:26.903+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:04:26.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T20:04:57.072+0000] {processor.py:186} INFO - Started process (PID=1421) to work on /opt/airflow/dags/test.py
[2025-03-25T20:04:57.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:04:57.077+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:04:57.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:04:57.172+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:04:57.171+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:04:57.173+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:04:57.186+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:04:57.186+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:04:57.194+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:04:57.194+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:04:57.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T20:05:27.642+0000] {processor.py:186} INFO - Started process (PID=1434) to work on /opt/airflow/dags/test.py
[2025-03-25T20:05:27.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:05:27.647+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:05:27.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:05:27.742+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:05:27.741+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:05:27.743+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:05:27.756+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:05:27.756+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:05:27.763+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:05:27.763+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:05:27.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.140 seconds
[2025-03-25T20:05:58.222+0000] {processor.py:186} INFO - Started process (PID=1447) to work on /opt/airflow/dags/test.py
[2025-03-25T20:05:58.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:05:58.226+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:05:58.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:05:58.321+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:05:58.321+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:05:58.322+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:05:58.336+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:05:58.336+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:05:58.343+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:05:58.343+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:05:58.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T20:06:28.702+0000] {processor.py:186} INFO - Started process (PID=1470) to work on /opt/airflow/dags/test.py
[2025-03-25T20:06:28.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:06:28.706+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:06:28.706+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:06:28.799+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:06:28.799+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:06:28.800+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:06:28.814+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:06:28.814+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:06:28.821+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:06:28.821+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:06:28.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.140 seconds
[2025-03-25T20:06:59.268+0000] {processor.py:186} INFO - Started process (PID=1483) to work on /opt/airflow/dags/test.py
[2025-03-25T20:06:59.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:06:59.272+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:06:59.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:06:59.367+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:06:59.366+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:06:59.368+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:06:59.381+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:06:59.381+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:06:59.388+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:06:59.388+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:06:59.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.138 seconds
[2025-03-25T20:07:29.576+0000] {processor.py:186} INFO - Started process (PID=1494) to work on /opt/airflow/dags/test.py
[2025-03-25T20:07:29.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:07:29.578+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:07:29.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:07:29.673+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:07:29.672+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:07:29.674+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:07:29.687+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:07:29.687+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:07:29.695+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:07:29.695+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:07:29.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.140 seconds
[2025-03-25T20:08:00.192+0000] {processor.py:186} INFO - Started process (PID=1507) to work on /opt/airflow/dags/test.py
[2025-03-25T20:08:00.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:08:00.195+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:08:00.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:08:00.290+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:08:00.289+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:08:00.291+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:08:00.303+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:08:00.303+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:08:00.311+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:08:00.310+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:08:00.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T20:08:30.360+0000] {processor.py:186} INFO - Started process (PID=1525) to work on /opt/airflow/dags/test.py
[2025-03-25T20:08:30.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:08:30.365+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:08:30.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:08:30.457+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:08:30.456+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:08:30.458+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:08:30.471+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:08:30.471+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:08:30.479+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:08:30.479+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:08:30.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2025-03-25T20:09:00.962+0000] {processor.py:186} INFO - Started process (PID=1540) to work on /opt/airflow/dags/test.py
[2025-03-25T20:09:00.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:09:00.967+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:09:00.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:09:01.061+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:09:01.061+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:09:01.062+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:09:01.075+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:09:01.075+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:09:01.083+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:09:01.083+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:09:01.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T20:09:31.822+0000] {processor.py:186} INFO - Started process (PID=1557) to work on /opt/airflow/dags/test.py
[2025-03-25T20:09:31.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:09:31.826+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:09:31.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:09:31.921+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:09:31.921+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:09:31.923+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:09:31.935+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:09:31.935+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:09:31.943+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:09:31.943+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:09:31.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.132 seconds
[2025-03-25T20:10:02.406+0000] {processor.py:186} INFO - Started process (PID=1572) to work on /opt/airflow/dags/test.py
[2025-03-25T20:10:02.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:10:02.407+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:10:02.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:10:02.501+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:10:02.501+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:10:02.503+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:10:02.515+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:10:02.515+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:10:02.522+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:10:02.522+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:10:02.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.131 seconds
[2025-03-25T20:10:32.732+0000] {processor.py:186} INFO - Started process (PID=1596) to work on /opt/airflow/dags/test.py
[2025-03-25T20:10:32.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:10:32.733+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:10:32.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:10:32.825+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:10:32.824+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:10:32.826+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:10:32.838+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:10:32.838+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:10:32.845+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:10:32.845+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:10:32.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-03-25T20:11:03.395+0000] {processor.py:186} INFO - Started process (PID=1620) to work on /opt/airflow/dags/test.py
[2025-03-25T20:11:03.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:11:03.396+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:11:03.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:11:03.489+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:11:03.488+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:11:03.490+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:11:03.503+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:11:03.503+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:11:03.510+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:11:03.510+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:11:03.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.134 seconds
[2025-03-25T20:11:33.929+0000] {processor.py:186} INFO - Started process (PID=1644) to work on /opt/airflow/dags/test.py
[2025-03-25T20:11:33.932+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:11:33.933+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:11:33.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:11:34.027+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:11:34.027+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:11:34.029+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:11:34.041+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:11:34.041+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:11:34.048+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:11:34.048+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:11:34.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.129 seconds
[2025-03-25T20:12:04.429+0000] {processor.py:186} INFO - Started process (PID=1665) to work on /opt/airflow/dags/test.py
[2025-03-25T20:12:04.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-25T20:12:04.433+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:12:04.433+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-25T20:12:04.526+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:12:04.526+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-03-25T20:12:04.528+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-03-25T20:12:04.541+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:12:04.541+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-25T20:12:04.548+0000] {logging_mixin.py:190} INFO - [2025-03-25T20:12:04.548+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-03-25T20:12:04.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.140 seconds
