[2024-12-30T07:15:01.467+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/test.py
[2024-12-30T07:15:01.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:15:01.481+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:01.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:15:01.884+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:01.883+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:15:01.896+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:15:02.173+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.172+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:test
[2024-12-30T07:15:02.188+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.188+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:test
[2024-12-30T07:15:02.199+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.199+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:test
[2024-12-30T07:15:02.214+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.214+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:test
[2024-12-30T07:15:02.225+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.225+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:test
[2024-12-30T07:15:02.236+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.236+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:test
[2024-12-30T07:15:02.248+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.247+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:test
[2024-12-30T07:15:02.248+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.248+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:15:02.264+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.263+0000] {dag.py:3262} INFO - Creating ORM DAG for test
[2024-12-30T07:15:02.265+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:02.265+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:15:02.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.844 seconds
[2024-12-30T07:15:33.020+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/test.py
[2024-12-30T07:15:33.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:15:33.028+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:33.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:15:33.243+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:33.242+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:15:33.246+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:15:33.272+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:33.272+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:15:33.285+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:15:33.285+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:15:33.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.564 seconds
[2024-12-30T07:16:04.389+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/test.py
[2024-12-30T07:16:04.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:16:04.393+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:16:04.393+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:16:04.629+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:16:04.628+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:16:04.633+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:16:04.661+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:16:04.661+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:16:04.675+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:16:04.674+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:16:04.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.316 seconds
[2024-12-30T07:16:35.351+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/test.py
[2024-12-30T07:16:35.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:16:35.354+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:16:35.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:16:35.511+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:16:35.510+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:16:35.513+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:16:35.541+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:16:35.540+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:16:35.554+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:16:35.554+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:16:35.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.251 seconds
[2024-12-30T07:17:06.084+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/test.py
[2024-12-30T07:17:06.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:17:06.088+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:17:06.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:17:06.265+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:17:06.264+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:17:06.268+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:17:06.294+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:17:06.294+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:17:06.306+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:17:06.306+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:17:06.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.267 seconds
[2024-12-30T07:17:36.836+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/test.py
[2024-12-30T07:17:36.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:17:36.841+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:17:36.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:17:37.074+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:17:37.073+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:17:37.077+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:17:37.105+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:17:37.105+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:17:37.122+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:17:37.122+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:17:37.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.335 seconds
[2024-12-30T07:18:07.626+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/test.py
[2024-12-30T07:18:07.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:18:07.629+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:18:07.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:18:07.821+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:18:07.821+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:18:07.824+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:18:07.846+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:18:07.846+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:18:08.019+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:18:08.018+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:18:08.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.433 seconds
[2024-12-30T07:18:38.563+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/test.py
[2024-12-30T07:18:38.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:18:38.567+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:18:38.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:18:38.714+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:18:38.713+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:18:38.716+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:18:38.738+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:18:38.738+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:18:38.888+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:18:38.888+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:18:38.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.350 seconds
[2024-12-30T07:19:09.442+0000] {processor.py:186} INFO - Started process (PID=154) to work on /opt/airflow/dags/test.py
[2024-12-30T07:19:09.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:19:09.447+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:19:09.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:19:09.600+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:19:09.599+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:19:09.602+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:19:09.797+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:19:09.797+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:19:09.808+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:19:09.808+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:19:09.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.407 seconds
[2024-12-30T07:19:40.396+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/test.py
[2024-12-30T07:19:40.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:19:40.400+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:19:40.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:19:40.722+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:19:40.721+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:19:40.725+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:19:40.747+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:19:40.746+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:19:40.757+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:19:40.757+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:19:40.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.388 seconds
[2024-12-30T07:20:11.655+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/test.py
[2024-12-30T07:20:11.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:20:11.668+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:20:11.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:20:11.826+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:20:11.825+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:20:11.829+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:20:11.853+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:20:11.853+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:20:11.865+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:20:11.864+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:20:11.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2024-12-30T07:20:42.430+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/dags/test.py
[2024-12-30T07:20:42.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:20:42.436+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:20:42.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:20:42.662+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:20:42.661+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:20:42.665+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:20:42.690+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:20:42.690+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:20:42.706+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:20:42.705+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:20:42.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.542 seconds
[2024-12-30T07:21:13.508+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/test.py
[2024-12-30T07:21:13.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:21:13.512+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:21:13.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:21:13.712+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:21:13.711+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:21:13.716+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:21:13.746+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:21:13.746+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:21:13.966+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:21:13.966+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:21:14.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.507 seconds
[2024-12-30T07:21:44.559+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/test.py
[2024-12-30T07:21:44.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:21:44.563+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:21:44.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:21:44.739+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:21:44.737+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:21:44.741+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:21:44.984+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:21:44.984+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:21:44.997+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:21:44.996+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:21:45.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.483 seconds
[2024-12-30T07:22:15.593+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/test.py
[2024-12-30T07:22:15.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:22:15.597+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:22:15.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:22:15.904+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:22:15.903+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:22:15.906+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:22:15.927+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:22:15.927+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:22:15.941+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:22:15.941+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:22:15.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.388 seconds
[2024-12-30T07:22:46.502+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/test.py
[2024-12-30T07:22:46.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:22:46.508+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:22:46.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:22:46.848+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:22:46.847+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:22:46.850+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:22:46.870+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:22:46.870+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:22:46.881+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:22:46.881+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:22:46.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.408 seconds
[2024-12-30T07:23:17.517+0000] {processor.py:186} INFO - Started process (PID=232) to work on /opt/airflow/dags/test.py
[2024-12-30T07:23:17.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:23:17.522+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:23:17.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:23:17.697+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:23:17.696+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:23:17.700+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:23:17.731+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:23:17.730+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:23:17.751+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:23:17.751+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:23:17.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.285 seconds
[2024-12-30T07:23:48.374+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/test.py
[2024-12-30T07:23:48.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:23:48.379+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:23:48.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:23:48.536+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:23:48.535+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:23:48.538+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:23:48.564+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:23:48.563+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:23:48.740+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:23:48.740+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:23:48.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.409 seconds
[2024-12-30T07:24:19.320+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/test.py
[2024-12-30T07:24:19.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:24:19.324+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:24:19.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:24:19.519+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:24:19.518+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:24:19.522+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:24:19.547+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:24:19.547+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:24:19.710+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:24:19.709+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:24:19.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.418 seconds
[2024-12-30T07:24:50.257+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/test.py
[2024-12-30T07:24:50.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:24:50.260+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:24:50.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:24:50.413+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:24:50.412+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:24:50.416+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:24:50.588+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:24:50.588+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:24:50.600+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:24:50.600+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:24:50.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.394 seconds
[2024-12-30T07:25:21.352+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/test.py
[2024-12-30T07:25:21.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-12-30T07:25:21.356+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:25:21.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-12-30T07:25:21.720+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:25:21.719+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2024-12-30T07:25:21.722+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2024-12-30T07:25:21.764+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:25:21.764+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:25:21.780+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:25:21.779+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2024-12-30T07:25:21.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.460 seconds
